name: CI-CD Integration/w Github Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        node-version: [ '14.18.2' ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm ci

      - name: Static analysis
        run: |
          echo "Running ESLint static analysis"
          npm run lint
          echo "Running TypeScript static analysis"
          npm run build:prod
  security:
    name: Vulnerability Scan
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: dev
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: true
      matrix:
        node-version: [ '14.18.2' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Synk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        with:
          languages: ${{ matrix.node-version }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
